Check AWS credentials

diff --git a/packages/cloudquery/script/setup b/packages/cloudquery/script/setup
--- a/packages/cloudquery/script/setup
+++ b/packages/cloudquery/script/setup
@@ -8,3 +8,15 @@ echo "Creating .env file from .env.example"
 cp $DIR/../.env.example $DIR/../.env
 
 echo "Visit https://github.com/settings/tokens?type=beta to create a GitHub token, and add it to the .env file"
+
+echo "Checking AWS credentials"
+STATUS=$(aws sts get-caller-identity --profile developerPlayground 2>&1 || true)
+if [[ ${STATUS} =~ (ExpiredToken) ]]; then
+  echo "Credentials for the developerPlayground profile have expired. Please fetch new credentials."
+  exit 1
+elif [[ ${STATUS} =~ ("could not be found") ]]; then
+  echo "Credentials for the developerPlayground profile are missing. Please fetch some."
+  exit 1
+else
+  echo "AWS credentials are valid"
+fi
