use deployTools as test account

diff --git a/packages/cloudquery/script/start b/packages/cloudquery/script/start
--- a/packages/cloudquery/script/start
+++ b/packages/cloudquery/script/start
@@ -9,12 +9,12 @@ MAIN_ENV_FILE=$ROOT_DIR/.env
 LOCAL_ENV_FILE=$HOME/.gu/service_catalogue/secrets/.env
 
 echo "Checking AWS credentials"
-STATUS=$(aws sts get-caller-identity --profile developerPlayground 2>&1 || true)
+STATUS=$(aws sts get-caller-identity --profile deployTools 2>&1 || true)
 if [[ ${STATUS} =~ (ExpiredToken) ]]; then
-  echo "Credentials for the developerPlayground profile have expired. Please fetch new credentials, and run this script again."
+  echo "Credentials for the deployTools profile have expired. Please fetch new credentials, and run this script again."
   exit 1
 elif [[ ${STATUS} =~ ("could not be found") ]]; then
-  echo "Credentials for the developerPlayground profile are missing. Please fetch some, and run this script again."
+  echo "Credentials for the deployTools profile are missing. Please fetch some, and run this script again."
   exit 1
 else
   echo "AWS credentials are valid"
