Refactor DEV environment
This change aims to reduce the length of the `start` script.

We no longer install `libpq`, for the `pg_dump` command.
Instead, a `db-copy` container will run `pg_dump` against CODE,
and write files to disk.

These files are then mounted to a special location in the Postgres container,
which results in them being executed on launch.

diff --git a/packages/dev-environment/script/start b/packages/dev-environment/script/start
--- a/packages/dev-environment/script/start
+++ b/packages/dev-environment/script/start
@@ -9,101 +9,53 @@ MAIN_ENV_FILE=$ROOT_DIR/.env
 LOCAL_ENV_FILE=$HOME/.gu/service_catalogue/.env.local
 clear='\033[0m'
 cyan='\033[0;36m'
-yellow="\033[1;33m"
 
-step(){
+step() {
   ((STEP_COUNT++))
   echo -e "\n${cyan}Step ${STEP_COUNT}${clear}: $1"
 }
 
-step "Setting up libpq"
-if ! brew list "libpq" &>/dev/null; then
-    brew install "libpq"
-else
-    echo "libpq is already installed"
-fi
+checkAwsCredentials() {
+  step "Checking AWS credentials"
 
-get_db_password() {
-    step "Getting DB credentials"
-    SECRET_NAME=$(aws secretsmanager list-secrets \
-    --profile deployTools --region eu-west-1 \
-    --filters Key=tag-value,Values=CODE  | jq '.SecretList[].Name' | grep Postgres | tr -d '"')
-    SECRET_STRING=$(aws secretsmanager get-secret-value \
-    --secret-id "$SECRET_NAME" \
-    --profile deployTools --region eu-west-1 | jq '.SecretString | fromjson')
-    CODE_DB_PASSWORD=$(echo "$SECRET_STRING" | jq -r '.password')
-    CODE_HOST=$(echo "$SECRET_STRING" | jq -r '.host')
-    unset SECRET_STRING
-    unset SECRET_NAME
+  STATUS=$(aws sts get-caller-identity --profile deployTools 2>&1 || true)
+  if [[ ${STATUS} =~ (ExpiredToken) ]]; then
+    echo "Credentials for the deployTools profile have expired. Please fetch new credentials, and run this script again."
+    exit 1
+  elif [[ ${STATUS} =~ ("could not be found") ]]; then
+    echo "Credentials for the deployTools profile are missing. Please fetch some, and run this script again."
+    exit 1
+  else
+    echo "AWS credentials are valid"
+  fi
 }
 
-insert_into_db() {
-      PGPASSWORD=${DATABASE_PASSWORD}  psql \
-    -U postgres -h "${DATABASE_HOSTNAME}" -p 5432 -d "${DATABASE_NAME}" -f "$1.sql" -q
-    rm "$1.sql"
+startContainers() {
+  step "Launching Docker containers"
 
-    echo "Transfer of $1 data complete ✅"
+  if (docker info) 2>&1 >/dev/null; then
+    docker-compose -f "${DIR}/../docker-compose.yaml" --env-file "$MAIN_ENV_FILE" --env-file "$LOCAL_ENV_FILE" up -d --build
+  else
+    echo "Docker is not running. Please start Docker."
+    exit 1
+  fi
 }
 
-copy(){
-    echo "Copying table $1 to local database"
-    PGPASSWORD=${CODE_DB_PASSWORD} pg_dump \
-    -U postgres -h "${CODE_HOST}" -p 5432 -d "${DATABASE_NAME}" -t "$1" -f "$1.sql" \
-    --no-owner --no-privileges --inserts --data-only
+checkVpnConnection() {
+  step "Checking VPN connection"
 
-    insert_into_db "$1"
+  if ifconfig | grep -q '10.249.'; then
+    echo "You're connected to the VPN"
+  else
+    echo "You're not connected to VPN. Please connect and retry."
+    exit 1
+  fi
 }
 
-step "Checking AWS credentials"
-STATUS=$(aws sts get-caller-identity --profile deployTools 2>&1 || true)
-if [[ ${STATUS} =~ (ExpiredToken) ]]; then
-  echo "Credentials for the deployTools profile have expired. Please fetch new credentials, and run this script again."
-  exit 1
-elif [[ ${STATUS} =~ ("could not be found") ]]; then
-  echo "Credentials for the deployTools profile are missing. Please fetch some, and run this script again."
-  exit 1
-else
-  echo "AWS credentials are valid"
-fi
+main() {
+  checkVpnConnection
+  checkAwsCredentials
+  startContainers
+}
 
-get_db_password
-source "$MAIN_ENV_FILE"
-
-step "Launching Docker containers"
-if (docker info) 2>&1 >/dev/null; then
-  docker-compose -f "${DIR}/../docker-compose.yaml" --env-file "$MAIN_ENV_FILE" --env-file "$LOCAL_ENV_FILE" up -d --build
-else
-  echo "Docker is not running. Please start Docker."
-  exit 1
-fi
-
-step "Baselining DB"
-echo -e "${yellow}Please note that this will drop all tables in the local database${clear}"
-npm -w cli start migrate -- --stage DEV --confirm
-
-tables_to_copy=(
-  "snyk_issues"
-  "snyk_projects"
-  "galaxies_teams_table"
-  "github_team_repositories"
-  "github_teams"
-  "github_repositories"
-  "github_repository_branches"
-  "github_workflows"
-  "github_languages"
-  "aws_organizations_accounts"
-  "aws_organizations_account_parents"
-  "aws_organizations_organizational_units"
-  "aws_ec2_instances"
-  "aws_cloudformation_stacks"
-)
-
-for table in "${tables_to_copy[@]}"; do
-  copy "$table" &
-done
-
-wait
-
-step "Cleaning up"
-unset CODE_DB_PASSWORD
-unset CODE_HOST
+main
