fix: improve AWS credentials validation in migration script

diff --git a/packages/dev-environment/script/start-prisma-migrate-test b/packages/dev-environment/script/start-prisma-migrate-test
--- a/packages/dev-environment/script/start-prisma-migrate-test
+++ b/packages/dev-environment/script/start-prisma-migrate-test
@@ -17,10 +17,12 @@ step() {
 
 check_aws_credentials() {
   step "Checking AWS credentials"
-
   STATUS=$(aws sts get-caller-identity --profile deployTools 2>&1 || true)
   if [[ ${STATUS} =~ (ExpiredToken) ]]; then
     echo "Credentials for the deployTools profile have expired. Please fetch new credentials, and run this script again."
+    exit 1
+  elif [[ ${STATUS} =~ (InvalidClientTokenId) ]]; then
+    echo "Credentials for the deployTools profile are invalid. Please fetch new credentials, and run this script again."
     exit 1
   elif [[ ${STATUS} =~ ("could not be found") ]]; then
     echo "Credentials for the deployTools profile are missing. Please fetch some, and run this script again."
